apiVersion: v1
publisher: ibm-playground
name: rstudio
version: latest
type: VS Code extension
displayName: rstudio
title: rstudio
description: >- 
  A real browser preview inside your editor that you can debug.
icon: https://www-03.ibm.com/press/us/en/attachment/20190.wss?fileId=ATTACH_FILE2&fileName=ibmpos_blue.jpg
category: Programming Languages
repository: https://github.ibm.com/ibm-api-marketplace/playground-api-hub-extension
firstPublicationDate: '2021-08-21'
latestUpdateDate: '2017-03-23'
spec:
  extensions:
     - 'https://raw.githubusercontent.com/IBM/Developer-Playground/master/R/latest/Ikuyadeu.r-2.3.1.vsix
'
