
# Copyright 2020 IBM.


apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-agent
  labels:
    app: virtual-agent
    tier: va
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtual-agent
  template:
    metadata:
      labels:
        app: virtual-agent
    spec:
      containers:
      - name: virtual-agent
        image: us.icr.io/smartthings/my-watson-assistant-backend:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: app-config
        env:
          - name: CLOUDANT_URL
            valueFrom:
              secretKeyRef:
                name: va-secrets
                key: CLOUDANT_URL
          - name: PORT
            value: "3000"
        ports:
        - name: http
          containerPort: 3000
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: virtual-agent-svc
  labels:
    app: virtual-agent
    tier: va
spec:
  type: NodePort
  ports:
  - port:  3000
    nodePort: 30001
  selector:
   app: virtual-agent

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DEBUG: "*"
  NODE_ENV: "development"
  PORT: "3000"
  HTTPS: "false"
  APP_CONFIG_KEY: "APP_CONFIG"

---

apiVersion: v1
kind: Secret
metadata:
  name: va-secrets
type: Opaque
data:
  CLOUDANT_URL: aHR0cHM6Ly8yMzIyYTNhYy0xM2Q5LTRjZmItYWVlOS1hZGNlN2VlODEyNmEtYmx1ZW1peDplOWU5NzQ0YTI4N2M1NjU4ZDUzOTkyZjVmYWJmMzU0NDM1NWQxOWMyMWZkMTlmOTVhYTNiYThhM2Y3MmJkNzZhQDIzMjJhM2FjLTEzZDktNGNmYi1hZWU5LWFkY2U3ZWU4MTI2YS1ibHVlbWl4LmNsb3VkYW50LmNvbQ==



