kind: Deployment
apiVersion: apps/v1
metadata:
  name: smart-virtual-assistant-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-virtual-assistant-deployment
  template:
    metadata:
      labels:
        app: smart-virtual-assistant-deployment
    spec:
      containers:
        - name: smart-virtual-assistant-deployment
          image: IMAGE_NAME
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: smart-virtual-assistant-deployment
spec:
  type: NodePort
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      nodePort: 31000
  selector:
    app: smart-virtual-assistant-deployment