kind: Deployment
apiVersion: apps/v1
metadata:
  name: churn-prediction-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: churn-prediction-deployment
  template:
    metadata:
      labels:
        app: churn-prediction-deployment
    spec:
      containers:
        - name: churn-prediction-deployment
          image: IMAGE_NAME
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: churn-prediction-deployment
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      nodePort: 31000
  selector:
    app: churn-prediction-deployment
