apiVersion: v1
kind: Pod
spec:
 containers:
   - image: quay.io/devplayground/developer-container-utilities:latest
     args:
       - sleep
       - "infinity"
     securityContext:
       privileged: true
