apiVersion: v1
kind: Pod
metadata:
 name: podman
spec:
 containers:
   - name: container
     image: quay.io/devplayground/developer-container-utilities:latest
     args:
       - sleep
       - "infinity"
     securityContext:
       privileged: true