## NOTE THAT THESE ARE BASE64 ENCODED VALUES using command eg. "echo -n 'mongodb' | base64"
## MAKE SURE THAT TRAILING WHITESPACES ARE NOT ENCODED
## To decode > echo 'YWRtaW4=' | base64 --decode

apiVersion: v1
kind: Secret
metadata:
  name: va-secrets
type: Opaque
data:
  CLOUDANT_URL: aHR0cHM6Ly8yMzIyYTNhYy0xM2Q5LTRjZmItYWVlOS1hZGNlN2VlODEyNmEtYmx1ZW1peDplOWU5NzQ0YTI4N2M1NjU4ZDUzOTkyZjVmYWJmMzU0NDM1NWQxOWMyMWZkMTlmOTVhYTNiYThhM2Y3MmJkNzZhQDIzMjJhM2FjLTEzZDktNGNmYi1hZWU5LWFkY2U3ZWU4MTI2YS1ibHVlbWl4LmNsb3VkYW50LmNvbQ==

---








