apiVersion: 1.0.0
metadata:
  name: sample-app
attributes:
  persistVolumes: 'false'
components:
- mountSources: true
    endpoints:
      - name: access-react-web-app
        port: 3001
    memoryLimit: 2Gi
    type: kubernetes
    reference: 'https://raw.github.ibm.com/ibm-api-marketplace/playground-resources/master/development/yaml/podmanconfig.yaml?token=AAB3L5TQXMXF2JJRAJW7LI3BS55TQ'
    image: 'quay.io/devplayground/developer-container-utilities:latest'
    alias: nodejs
  - id: redhat/vscode-didact/latest
    type: chePlugin
    preferences:
      didact.disableNotifications: true
      didact.openDefaultTutorialAtStartup: false
  - id: ibm-playground/api-hub/latest
    type: chePlugin
  - id: eclipse/che-theia/latest
    memoryLimit: 4Gi
    type: cheEditor
