apiVersion: 1.0.0
metadata:
  name: sample-app
attributes:
  persistVolumes: 'false'
components:
  - mountSources: true
    endpoints:
      - name: access-react-web-app
        port: 3001
    memoryLimit: 2Gi
    type: dockerimage
    image: 'quay.io/apihub/che-nodejs-python:latest'
    alias: nodejs
  - id: redhat/vscode-didact/latest
    type: chePlugin
  - id: ibm-playground/api-hub/latest
    type: chePlugin

