apiVersion: 1.0.0
metadata:
  name: sample-app
attributes:
  persistVolumes: 'false'
components:
  - id: ibm-playground/api-hub/latest
    type: chePlugin
  - id: redhat/vscode-didact/latest
    type: chePlugin
