apiVersion: 1.0.0
metadata:
  name: sample-app
attributes:
  persistVolumes: 'false'
components:
   - mountSources: true
    endpoints:
      - name: nodejs
        port: 4100
    memoryLimit: 2Gi
    type: dockerimage
    image: 'quay.io/pgirishibm/che-nodejs-python:latest'
    alias: nodejs
  - id: ibm-playground/api-hub/latest
    type: chePlugin
  - id: redhat/vscode-didact/latest
    type: chePlugin
