apiVersion: 1.0.0
metadata:
  name: sample-app
attributes:
  persistVolumes: 'false'
components:
  - mountSources: true
    endpoints:
      - name: access-react-web-app
        port: 3001
    memoryLimit: 2Gi
    type: dockerimage
    alias: sandbox
    image: 'quay.io/devplayground/developer-container-utilities:latest'
  - id: redhat/vscode-didact/latest
    type: chePlugin
    preferences:
      didact.disableNotifications: true
      didact.openDefaultTutorialAtStartup: true
      didact.autoAddDefaultTutorials: false
      didact.defaultUrl: 'https://raw.githubusercontent.com/IBM/Developer-Playground/development/didact/welcome.md'
  - id: ibm-playground/api-hub/latest
    type: chePlugin
  - id: eclipse/che-theia/latest
    memoryLimit: 4Gi
    type: cheEditor
