apiVersion: 1.0.0
metadata:
  name: sample-app
attributes:
  persistVolumes: 'false'
components:
  - mountSources: true
    type: kubernetes
    reference: 'https://raw.githubusercontent.com/IBM/Developer-Playground/master/terminal-config/podman.yaml'
    alias: podman
  - mountSources: true
    endpoints:
      - name: access-react-web-app
        port: 3001
    memoryLimit: 2Gi
    type: dockerimage
    alias: nodejs
    image: 'quay.io/devplayground/developer-container-utilities-nodejs:latest'
  - id: ibm-playground/api-hub/latest
    type: chePlugin
  - id: eclipse/che-theia/latest
    memoryLimit: 4Gi
    type: cheEditor
